### ISSUE TITLE
Investigate Vagrant Azure Provider

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm-jenkinsscripts#64]
**Summary**
As OSCM pipelines are heading to be run in the cloud, Vagrant Azure provider could one of the solution which we want to have a closer look at

**Details**
As a start, we could try to setup vagrant with azure to provision vm and run on it some simple ansible playbook

**Acceptance criteria**
TBD

**Additional context**
https://github.com/Azure/vagrant-azure

**Comment by GoebelL** [comment]
Hey @kowalczyka, @cworf91 Clearly it fits better to use the Azure services here, since we already have built the OIDC infrastructure and tenant accounts in Azure cloud. In this case, we should go with [Azure Key Vault](https://docs.microsoft.com/en-us/azure/developer/ansible/key-vault-configure-vm-security) to manage the secrets, rather than with HashiCorp vault or any other external provider. 
We should create a Key Vault and configure it's access for that application with a service principal that we define in the Azure Portal only. In this way we can manage the vault independently and reprovision our Azure instances anytime we need without losing the secrets.

**Comment by kowalczyka** [comment]
Closing the issue as investigation part is done. 
As configuration with two nodes is working - https://github.com/servicecatalog/oscm-jenkinsscripts/pull/79, the next step would be to run all CI jobs with it - https://github.com/servicecatalog/oscm-jenkinsscripts/issues/78
